# Generated by Django 5.0.2 on 2025-04-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill (e.g., Python, JavaScript)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='How the skill should be displayed (e.g., Python, JavaScript)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this skill filter is active and should be shown')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the skill appears (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Filter',
                'verbose_name_plural': 'Skill Filters',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
